---
output: github_document
---

# Mini Project 3: Capstone

## Learning Goal

- Complete the entire data-scientific process to answer questions you have about some topic of your choosing
- Create an interactive report (i.e. Shiny app) to communicate your findings

## Due date

* The Shiny app, blog post, and presentation are due on GitHub by Monday, June 5 at 8:00 a.m. (This is our finals period.)

## Description

The goal of the project is to go through the complete data-scientific process to answer questions you have about some topic of your choosing. You will need to acquire your data, design your visualizations, run analyses (which could be visualizations), and communicate the results. The project is an opportunity to show off what you have learned about data science! Your task is to use data to tell us something interesting. This project is deliberately open-ended to allow you to fully explore your creativity. Here are the main rules that must be followed:

**Create a Shiny app.** The app will be your platform to communicate what you have learned to your classmates.

**Use the materials learned in this class.** Both the computational and statistical tools learned.

**Your project must be centered around real data.** You will work with large, complex, and/or messy data. While this is not an explicit requirement of the project, the more challenging your data set is, the more you will have to use the tools learned in this class. For example, one thing that will make your data science project more ambitious is combining two or more data sets that are not directly related.

**Your project must tell us something.** An example of a project that doesn't tell us anything, would be something that downloads a single data source and summarizes it, with some perfunctory visualization. Make sure that your project is thought-provoking and has some underlying meaning!

**Cleverness and creativity will be rewarded.** Going above and beyond what we did in class will be rewarded.


You may work in groups of up to four, but you are not required to.

## Blog 

In your blog post, you should tell a data science audience about your project, why they should care about it, and what you have discovered. Your audience will be people like you: current or aspiring data scientists. Keep in mind that this audience is extraordinarily diverse in terms of skills and abilities, so you should assume very little about what they might know. However, your audience is reasonably tech-savvy, so you need not "dumb-down"" your analysis. Your write-up should make it clear to me and any other student in the class what methods and techniques you have used to produce your finished product.

#### Content

Do not present all of the R code that you wrote throughout the process of working on this project. In fact

- The amount of R code in the outputted document should be minimal. The less R code the better.
- Important conclusions should appear in the main text, not in comments in the code.
- The R markdown file should contain the necessary and sufficient (i.e. minimal) set of R code that is necessary to understand your results and findings. If you make a claim, it must be justified by explicit calculation. A knowledgeable reviewer should be able to reproduce your analysis:
    + Compile your .Rmd file without modification
    + Verify every statement that you have made.
    
#### Motivation

Be sure to motivate your topic at the beginning of your write-up. You should try to hook the reader early on. Assume that your audience is a skeptical data scientist who has stumbled across your report but has very little time to read it. Can you give them a reason to continue reading? A cool visualization or result can help.




## GitHub

As with the other mini projects, you will use GitHub to collaborate with your, as well as to submit the final product. To create a repository for your mini project, complete the following steps:

1. Nominate one person to host your repository. Suppose this person's GitHub username is `github_id`.
2. Have `github_id` fork the [`mini-project-3`](https://github.com/cmsc205/mini-project-3) repository from `cmsc205`
3. Have `github_id` add other teammates as "Collaborators" (under "Settings")
4. All teammates:
    1. Open new project in RStudio...
    2. From Version Control...
    3. From GitHub...
    4. Paste the "Clone or download" URL from `github_id/mini-project-2`’s repo

To submit your final blog post, please follow the instructions from [`HW-0`](https://github.com/cmsc205/HW-0)


## Acknowledgements
The project description was adapted from Albert Kim, CS109 at Harvard, and Ben Baumer and Jordan Crouser.